version: '3'
services:
    discord_bot:
        build: ./discord_bot
        env_file:
            - .env
        depends_on:
            - db
    db:
        build: ./db
        expose:
            - '3306'
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        restart: always
volumes:
    db:
